name: Test Suite

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  test:
    name: Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        node-version: [18.x, 20.x, 21.x]
        os: [ubuntu-latest, windows-latest, macos-latest]
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install dependencies
      shell: bash
      run: |
        if [ -f package-lock.json ]; then
          npm ci
        else
          npm install
        fi
      
    - name: Install src dependencies
      shell: bash
      run: |
        cd src
        if [ -f package-lock.json ]; then
          npm ci
        else
          npm install
        fi
      
    - name: Run unit tests
      shell: bash
      run: npm run test:unit
      
    - name: Run integration tests
      shell: bash
      run: npm run test:integration
      
    - name: Run all tests
      shell: bash
      run: npm run test:all
      
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results-${{ matrix.os }}-${{ matrix.node-version }}
        path: |
          test-results/
          coverage/
        retention-days: 7
        
    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: logs-${{ matrix.os }}-${{ matrix.node-version }}
        path: |
          logs/
          *.log
        retention-days: 7

  lint:
    name: Code Quality
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install dependencies
      shell: bash
      run: |
        if [ -f package-lock.json ]; then
          npm ci
        else
          npm install
        fi
      
    - name: Install src dependencies
      shell: bash
      run: |
        cd src
        if [ -f package-lock.json ]; then
          npm ci
        else
          npm install
        fi
      
    - name: Check package.json
      shell: bash
      run: |
        echo "Validating package.json..."
        node -e "JSON.parse(require('fs').readFileSync('package.json', 'utf8'))"
        echo "package.json is valid"
      
    - name: Check for console.log statements
      shell: bash
      run: |
        echo "Checking for console.log statements in production code (excluding tests and CLI help)..."
        if grep -r "console.log" src/ --exclude-dir=node_modules --exclude="*.test.js" --exclude="*test*.js" --exclude="cli.js" | grep -v "showBeautifulHelp\|test.*console.log"; then
          echo "❌ Found console.log statements in production source code"
          exit 1
        else
          echo "✅ No console.log statements found in production code"
        fi

  security:
    name: Security Audit
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install dependencies
      shell: bash
      run: |
        if [ -f package-lock.json ]; then
          npm ci
        else
          npm install
        fi
      
    - name: Install src dependencies
      shell: bash
      run: |
        cd src
        if [ -f package-lock.json ]; then
          npm ci
        else
          npm install
        fi
      
    - name: Run security audit
      shell: bash
      run: npm audit --audit-level=moderate
      
    - name: Check for known vulnerabilities
      shell: bash
      run: |
        echo "Checking for high severity vulnerabilities..."
        npm audit --audit-level=high || true
        if npm audit --audit-level=high 2>&1 | grep -q "found 0 vulnerabilities"; then
          echo "✅ No high severity vulnerabilities found"
        else
          echo "❌ High severity vulnerabilities found"
          exit 1
        fi

  build:
    name: Build Verification
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install dependencies
      shell: bash
      run: |
        if [ -f package-lock.json ]; then
          npm ci
        else
          npm install
        fi
      
    - name: Install src dependencies
      shell: bash
      run: |
        cd src
        if [ -f package-lock.json ]; then
          npm ci
        else
          npm install
        fi
      
    - name: Verify build
      shell: bash
      run: |
        # Test that the main entry point works
        node -e "import('./src/index.js').then(() => console.log('✅ Main entry point works')).catch(e => { console.error('❌ Main entry point failed:', e.message); process.exit(1); })"
        
        # Test that CLI can be executed (with help flag to avoid actual execution)
        node src/cli.js --help > /dev/null 2>&1 && echo "✅ CLI execution works" || echo "❌ CLI execution failed"
        
        # Test that config file exists and is valid JSON
        ls -la src/config/ && node -e "import('fs/promises').then(fs => fs.readFile('src/config/config.json', 'utf8').then(data => { JSON.parse(data); console.log('✅ Config file is valid JSON'); })).catch(e => { console.error('❌ Config file validation failed:', e.message); process.exit(1); })"
        
        echo "✅ Build verification completed"
